### ISSUE TITLE
Stack snapshot tests keep failing

### ISSUE THREAD

**Issue by Bakkenrak** [cremich/kiko-backend#22]
The snapshot tests fail due to resource hash values apparently changing a lot depending on actual stack changes but also just  due to where they're run. For instance a newly updated snapshot that's working on one machine fails in the Github workflow.

An approach could be to ignore them as described [here](https://lanwen.ru/posts/ignore-jest-snapshot-diffs/).

**Comment by cremich** [comment]
I am preparing a change to get rid of the snapshot tests with something more meaningful. Will take care of it!
