### ISSUE TITLE
Deploying the application fails

### ISSUE THREAD

**Issue by timvancleef** [cremich/kiko-backend#28]
Following the instructions in the README i tried to deploy the kiko-backend to AWS using cdk.
The deployment for `dev-kiko-pool-management` went fine, but when cdk tried deploying `dev-kiko-tenant-management` the CloudFormation stack creation was aborted with the following error:

```
Domain already associated with another user pool. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 911ac4c0-42cf-4bf3-a4b4-e980e22cbf99; Proxy: null)
```

Not sure what domain can already associated with another user pool and why, since this was the very first time i tried deploying the app 🤷‍♀️ 

Since i am not that familiar with CloudFormation and AWS in general i started looking into `bin/kiko.js` and saw that the userpool domain prefix is generated using `kiko-${deployStage}`.

In the end i was able to deploy `kiko-backend` using something different for `deployStage` (i simply used `test-dev` 🤓).

Not sure if this a bug or expected behaviour, though.
If this is expected behaviour i would suggest adding this to the README.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - CDK version (using npx): 1.100.0 (build d996c6d)

**Comment by cremich** [comment]
This is a good catch. It seems that the domain for userpool is global over all deployments. As I have the stack deployed in my own account, we need something like a unique id as part of the domain name. Maybe the AWS AccountId could work.

**Comment by cremich** [comment]
I found out, that we only need the user pool domain if we want to use hosted login. As we use the amplify UI widgets in the kiko-frontend, we can completely remove the user pool domain resource (see linked PR)
