### ISSUE TITLE
Account requires additional review prior to being able to send SMS messages

### ISSUE THREAD

**Issue by Bakkenrak** [cremich/kiko-backend#34]
I finally got around to trying to send me an SMS. I didn't receive one and saw no errors in the logs or CloudTrail. After further investigation Pinpoint campaign details show that one SMS was sent but none were delivered, resulting in a delivery rate of 0%.

Only when I tried to send myself another message via pinpoint's test feature, it showed me this:

> Message not sent: We weren't able to send your SMS message to +49172xxxxxxx.
> Details
> Request Id 415 : Your account requires additional review prior to being able to send SMS messages. Please create a support ticket with an explanation of your use case. https://console.aws.amazon.com/support/cases#/create?issueType=service-limit-increase&limitType=service-code-sns-text-messaging

I reckon you went through that process @cremich ? Should this maybe be noted in the Readme?

More importantly, alerting on the delivery rate of campaigns would be good to have. Failure to deliver the message, moreover silently, undermines the whole idea.

**To Reproduce**
Use an AWS account that was never used/unlocked for SMS sending before.

**Comment by cremich** [comment]
@Bakkenrak interesting. I can't really remember, if there were some additionale actions required. I had once the problem that my monthly spending quota on SMS budget exceeded in my account: https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-sms-awssupport-spend-threshold.html

Is this error related to https://github.com/cremich/kiko-backend/pull/35 ? Or do you also get the error using the current `main` branch?

But @timvancleef you recently configured the backend in your account. Do observed similar issues?

**Comment by cremich** [comment]
I rolled out a new account in my landing zone and will also try to test it in a fresh setup.

**Comment by Bakkenrak** [comment]
I got this error with the latest main branch as of the day of creating this issue. So I started #35 to be informed of such problems.
I'm not sure if my account is maybe a special case because it's kinda old and maybe quotas were initialized differently back then. 
I think raising the awareness that a service level increase could be needed in a new account via the Readme should suffice and the alarm would make it even more clear when such a problem occurs.

**Comment by timvancleef** [comment]
Hi there,
yeah i configured everything a few days back and as far as i remember i didn't have to do any extra steps 🤔 
I was following the readme of the backend, started the frontend, connected it to the deployt backend, reported positive test results in the browser and immediately got the SMS notification.
